### ISSUE TITLE
[Question] is there an option guard register route?

### ISSUE THREAD

**Issue by arnoldtkl** [perfood/couch-auth#32]
Hi, thanks for maintaining this library! I appreciate the effort to keep this library updated constantly. 

I was just wondering if there is an option to guard the register route with logged in users? Because I have a private system which does not allow public users to register or login.

**Comment by LyteFM** [comment]
Have a look at [requireAuth](https://github.com/perfood/couch-auth#securing-your-routes). It should be possible to intercept requests to `/register` with an auth check before passing them on.

**Comment by arnoldtkl** [comment]
Ok, thanks for the guidance!
