### ISSUE TITLE
Mailer option not working with nodemailer-ses-transport

### ISSUE THREAD

**Issue by Sourav-techlur** [perfood/couch-auth#62]
Hello,

I was trying to integrate the nodemailer-ses-transport to send the email but it is throwing me the following error

![image](https://user-images.githubusercontent.com/60867326/198208431-3c7c7085-10bc-4fe5-b5d8-fab4c69d1c99.png)

my configuration is as follows
`
const sesTransporter = require('nodemailer-ses-transport');

mailer: {
      fromEmail: 'noreply@domain.com',
      transport: sesTransporter,
      provider: 'ses',
      options: {
        accessKeyId: 'access key',
        secretAccessKey: 'secret access key',
        region: 'region',
        bucket: 'bucket',
      },
}
`

I am using node version 16.

**Comment by Sourav-techlur** [comment]
I have resolved it. Thanks

**Comment by LyteFM** [comment]
Good to hear, was the problem related to `couch-auth`? Feel free to share the solution in a comment ;)
